package com.demo;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "company")
public class Company {
	

	 // ==============
	  // PRIVATE FIELDS
	  // ==============

	  // An autogenerated id (unique for each user in the db)
	  @Id
	  private String idcompany;

	  // The user email
	  @NotNull
	  private String companyname;


	  // ==============
	  // PUBLIC METHODS
	  // ==============

	  public Company() { }

	  public Company(String idcompany, String companyname) {
	    this.idcompany = idcompany;
	    this.companyname=companyname;
	  }
	  

	public String getidcompany() {
		return idcompany;
	}

	public void setidcompany(String idcompany) {
		this.idcompany = idcompany;
	}

	public String getcompanyname() {
		return companyname;
	}

	public void setcompanyname(String companyname) {
		this.companyname = companyname;
	}

	 
	public String toString()
	{
		return companyname;
		
	}
	
	
}
